import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Notes app</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Notes App</a>
        </h1>

        <p>
          <Link href={'/login'}>Login</Link>
        </p>
        <p>
          <Link href={'/register'}>Register</Link>
        </p>
      </main>
    </div>
  )
}
